trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: install
  displayName: 'Install'

- task: Npm@1
  inputs:
    command: custom
    customCommand: run build --prod
  displayName: 'Build'

# - task: Npm@1
#   inputs:
#     command: custom
#     customCommand: run test-ci
#   displayName: 'Test with coverage'

# - task: PublishTestResults@2
#   inputs:
#     testResultsFormat: 'JUnit'
#     testResultsFiles: '**/TESTS-*.xml'
#     mergeTestResults: true
#     failTaskOnFailedTests: true

# - task: PublishCodeCoverageResults@1
#   inputs:
#     codeCoverageTool: 'Cobertura'
#     summaryFileLocation: '**/cobertura-coverage.xml'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go (d6a4c45c-86db-4898-b05c-ee5daf6a1c3b)'
    appType: 'webApp'
    WebAppName: 'moving-square'
    deployToSlotOrASE: true
    ResourceGroupName: 'moving-square'
    SlotName: 'production'
    packageForLinux: 'www/'